var jsl,md5,html,html2,http,top,dc,login;login=login||(function(){"use strict";var lib={},gXhr=null,gXhrDsl=null,gXhrPushBtn=null,gData=null,gDialog=null,gDialogContent=null,gFacErr=null,gFormElem=null,gUsernameElem=null,gPassElem=null;function showLogin(){if(gXhr){gXhr.stop();}
jsl.setText("dialogTitle",gData.pageTitle);jsl.setText(gFacErr,"");gFacErr=null;jsl.removeClass(gDialog,"forgotPass");jsl.removeClass(gDialog,"pushmail");jsl.removeClass(gDialog,"setFac");jsl.removeClass(gDialog,"wait");}
function reloadPage(href){var a=html2.a({href:href||""}),clickEvt=null;html2.add(document.body,a);if(a.click){a.click();}else if(document.dispatchEvent){clickEvt=document.createEvent("MouseEvent");clickEvt.initEvent("click",true,true);a.dispatchEvent(clickEvt);}else if(document.fireEvent){a.fireEvent('onclick');}
document.body.removeChild(a);}
function ajaxWaitForBox(){var callback,url=encodeURI("/"),countRetries=0,boxStillOnline=true,requestTimeout=5000,xhr;function goToBox(){top.location.href="/start";}
function doRequest(){xhr=http.request({method:"POST",url:url,params:{},callback:callback});xhr.start();}
callback=function(resp){if(resp&&false===resp.answer){boxStillOnline=false;window.setTimeout(doRequest,requestTimeout);}else{if(boxStillOnline){countRetries+=1;if(6<countRetries){window.setTimeout(goToBox,5000);}
window.setTimeout(doRequest,requestTimeout);}else{window.setTimeout(goToBox,30000);}}};window.setTimeout(doRequest,requestTimeout);}
function createFacErr(errCode){var tmpElem=null;if(!gFacErr){gFacErr=html2.div({"class":"restore"});html2.add(gDialogContent,gFacErr);if(0===errCode){html2.add(gFacErr,html2.div({id:"restore","class":"doReset"},html2.p({},gData.facIsSetTxt),html2.p({},gData.facPationsTxt),html2.div({"class":"intxt wait"}),html2.p({},gData.facWhatNextTxt)));ajaxWaitForBox();window.setTimeout(function(){reloadPage(gData.fallbackRedirectUrl);},300000);}else{if(2===errCode){tmpElem=html2.div({id:"restoreerror1"},html2.p({"class":"ErrorMsg"},gData.txt.facNotAllowed),html2.p({},gData.txt.facOnAllowedComp));}else{tmpElem=html2.div({id:"restoreerror2"},html2.p({"class":"ErrorMsg"},gData.txt.facFailed),html2.p({},gData.txt.facNotAllowedOr10Min),html2.p({},gData.txt.facDisconnectPower),html2.p({},gData.txt.facRepeat));}
html2.add(gFacErr,html2.div({id:"restoreerror"},html2.h4({},gData.txt.facNotSet),tmpElem));html2.add(gFacErr,html2.div({id:"toOvBtn","class":"btn_form_foot"},html2.button({type:"button",id:"reloadPageBtn",onclick:showLogin},gData.txt.back)));}}}
function cbSetFac(resp){if(resp&&"number"===typeof resp.restore_state){createFacErr(resp.restore_state);}else{createFacErr();}}
function showFacReset(){if(gData.fromInternet){showLogin();return;}
if(gXhr){gXhr.stop();}
jsl.addClass(gDialog,"setFac");jsl.addClass(gDialog,"wait");jsl.setText("dialogTitle",gData.facTitle);gXhr=http.request({method:"POST",url:"index.lua",type:"text",params:{reset:"1"},callback:function(){jsl.removeClass(gDialog,"wait");gXhr=http.request({method:"POST",url:"index.lua",params:{restore:"login"},callback:cbSetFac});gXhr.start();}});gXhr.start();}
function makeDots(str){var newStr="",i=0;for(i=0;i<str.length;i+=1){if(255<str.charCodeAt(i)){newStr+=".";}else{newStr+=str.charAt(i);}}
return newStr;}
function setFocus(){var elemToFocus=gPassElem;if(gUsernameElem&&!gUsernameElem.options&&""===gUsernameElem.value){elemToFocus=gUsernameElem;}
jsl.focus(elemToFocus);}
function generateResponse(password){var resp;if(gData.challenge.indexOf("$")>=0){return window.generatePBKDF2Response(gData.challenge,password);}
resp=gData.challenge+"-"+password;return Promise.resolve(gData.challenge+"-"+md5.hex(resp));}
function onLoginFormSubmit(){var dot_pass=null,resp=null;jsl.addClass("uiLoginError","hidden");jsl.removeClass(gPassElem,"error");if(gUsernameElem){if(0<gUsernameElem.value.length){jsl.addClass("uiUsernameError","hidden");jsl.removeClass(gUsernameElem,"error");jsl.setValue("username",gUsernameElem.value);}else{jsl.removeClass("uiUsernameError","hidden");jsl.addClass(gUsernameElem,"error");jsl.focus(gUsernameElem);return false;}}
jsl.disable(gUsernameElem);jsl.disable(gPassElem);jsl.disable("submitLoginBtn");jsl.setStyle(gFormElem,"cursor","wait");dot_pass=makeDots(gPassElem.value);generateResponse(dot_pass).then(function(response){jsl.setValue("uiResp",response);jsl.submitForm("loginForm");},function(err){console.warn(err);})
return false;}
function getWaitStr(mSec){var sec=Math.ceil(mSec/1000),txt="";if(1===sec){txt=gData.txt.waitOne;}else{txt=gData.txt.waitMore.replace(/%1/,sec);}
return txt;}
function doBlockLogin(blockTime){var start=(new Date()).getTime(),timer=null;jsl.disable(gUsernameElem);jsl.disable("username");jsl.disable(gPassElem);jsl.disable("submitLoginBtn");function f(){var now=(new Date()).getTime(),wait=blockTime-(now-start),hiddenTime;if(timer){window.clearTimeout(timer);}
if(0<wait){jsl.setHtml("uiWait",getWaitStr(wait));jsl.removeClass("uiLoginError","hidden");jsl.addClass(gPassElem,"error");timer=window.setTimeout(f,500);}else{timer=null;hiddenTime=10000-blockTime;if(0>=hiddenTime){hiddenTime=1;}
blockTime=0;window.setTimeout(function(){if(!blockTime){jsl.addClass("uiLoginError","hidden");}},hiddenTime);jsl.enable(gUsernameElem);jsl.enable("username");jsl.enable(gPassElem);setFocus();jsl.enable("submitLoginBtn");jsl.setHtml("uiWait",gData.txt.waitTryAgain);}}
f();}
function showPushMailSent(){if(gData.fromInternet){showLogin();return;}
jsl.addClass(gDialog,"wait");jsl.addClass(gDialog,"pushmail");if(gXhr){gXhr.stop();}
gXhr=http.request({method:"POST",url:"index.lua",type:"text",params:{pushmail:"1"},callback:function(){jsl.removeClass(gDialog,"wait");}});gXhr.start();}
function createForgotPass(){var parDiv=null,tmpObj=null,tmpObj2=null;if(gData.fromInternet){return;}
parDiv=html2.div({id:"forgotPass","class":"forgotPassForm"});if(gData.pushmailEnabled){if(gData.firstTenMin){html2.add(parDiv,html2.div({"class":"pushmailSend"},html2.h4({},gData.txt.sendLoginLink),html2.p({},gData.txt.loginMailSent)),html2.div({"class":"pushmailQuestion"},html2.h4({},gData.txt.sendLoginLink),html2.p({},gData.txt.loginLinkMailPossible),(gData.txt.loginLinkMailPossibleMyF&&html2.p({},gData.txt.loginLinkMailPossibleMyF))||"",html2.p({},gData.txt.pushNeedsWan),html2.div({"class":"btn_form"},html2.button({onclick:showPushMailSent,name:"pushmail",type:"button",id:"sendPushMail"},gData.txt.sendPushServiceMail))),html2.div({id:"setFac"},html2.hr({}),html2.h4({},gData.txt.setFacDefaults),html2.p({},gData.ifSetFacTxt),html2.div({},html2.span({"class":"WarnMsgBold"},gData.txt.caution),html2.p({},gData.txt.facLoseSettings)),html2.div({"class":"btn_form"},html2.button({onclick:showFacReset,name:"reset",type:"button",id:"sendFacReset"},gData.txt.setFacDefaults))));}else{html2.add(parDiv,html2.div({"class":"pushmailSend"},html2.h4({},gData.txt.sendLoginLink),html2.p({},gData.txt.loginMailSent)),html2.div({"class":"pushmailQuestion"},html2.h4({},gData.txt.sendLoginLink),html2.p({},gData.txt.loginLinkMailPossible),html2.toggleLink({closedText:gData.txt.pushNotWorking,destination:"#uiPushMore"}),html2.div({id:"uiPushMore","class":"hide"},html2.p({},gData.txt.pushNeedsWan),html2.p({},gData.ifSetFacTxt),html2.div({},html2.span({"class":"WarnMsgBold"},gData.txt.caution),html2.p({},gData.txt.facLoseSettings),html2.p({},gData.cutPowerTxt)))));}}else{html2.add(parDiv,html2.div({id:"setFac"},(gData.showFactoryPasswordHint&&html2.p({},gData.txt.hintPassword))||"",html2.p({},gData.ifSetFacTxt),html2.div({},html2.span({"class":"WarnMsgBold"},gData.txt.caution),html2.p({},gData.txt.facLoseSettings)),(!gData.firstTenMin&&html2.p({},gData.cutPowerTxt))||""));}
tmpObj="";tmpObj2="";if(gData.pushmailEnabled&&false===gData.firstTenMin){tmpObj=html2.button({onclick:showPushMailSent,name:"pushmail",type:"button",id:"sendPushMail"},gData.txt.sendPushServiceMail);}
if(!gData.pushmailEnabled&&gData.firstTenMin){tmpObj2=html2.button({onclick:showFacReset,name:"reset",type:"button",id:"sendFacReset"},gData.txt.setFacDefaults);}
html2.add(parDiv,html2.div({"class":"btn_form_foot"},html2.button({onclick:showLogin,type:"button",name:"cancel",id:"cancelForgotPass"},gData.txt.back),tmpObj,tmpObj2));html2.add(gDialogContent,parDiv);}
function showForgotPass(evt){if(gData.fromInternet){return jsl.cancelEvent(evt);}
if(!jsl.get("forgotPass")){createForgotPass();}
jsl.setText("dialogTitle",gData.txt.forgotPassword);jsl.addClass(gDialog,"forgotPass");return jsl.cancelEvent(evt);}
function reloadPagePushLogin(evt){location.reload();}
function createPushBtnLoginRestartHint(){gDialogContent.innerHTML="";jsl.setText("dialogTitle",gData.pageTitle);html2.add(gDialogContent,html2.div({"class":"formular"},html2.p({},gData.txt.pushLoginRestartExplain),html2.p({},gData.txt.pushLoginRestartRequest)),html2.div({id:"restartPushLoginBox","class":"btn_form_foot"},html2.button({type:"button",id:"reloadPageBtn",onclick:reloadPagePushLogin},gData.txt.pushLoginRestartBtn)));}
function doPushBtnPoll(data){if(gXhrPushBtn){gXhrPushBtn.stop();}
if(data){try{data=JSON.parse(data);}catch(evt){data={};}
if(data.sid){var tmpLp="",tmpLang="";if(gData.lastPage){tmpLp="&"+encodeURIComponent("lp")+"="+encodeURIComponent(gData.lastPage);}
if(gData.temp_language){tmpLang="&"+encodeURIComponent("temp_language")+"="+encodeURIComponent(gData.temp_language);}
dc.call("/?"+encodeURIComponent("sid")+"="+encodeURIComponent(data.sid)+tmpLp+tmpLang);}else if(data.pushLoginRestartRequired){createPushBtnLoginRestartHint();return;}}
gXhrPushBtn=http.request({method:"POST",url:"/push_btn_login.lua",type:"text",params:{sid:gData.sid},callback:doPushBtnPoll});window.setTimeout(function(){gXhrPushBtn.start();},2000);}
function createPushBtnLoginForm(){gDialogContent.innerHTML="";jsl.setText("dialogTitle",gData.pageTitle);html2.add(gDialogContent,html2.div({"class":"formular"},html2.p({},gData.txt.pushBtnWelcome)));doPushBtnPoll();}
function createLoginForm(){var form=null,formContent=null,formFoot=null,reasonTab=[],userOptions;var otherUserLink;var passwordLink;var usernameArea;var passwordLabel;formContent=html2.div({"class":"formular"});formFoot=html2.div({"class":"btn_form_foot"});form=html2.form({method:"post","action":"index.lua",id:"loginForm","class":"loginForm"},formContent,formFoot);html2.add(gDialogContent,form);if(gData.loginReason&&0<gData.loginReason&&6>gData.loginReason){reasonTab=["",gData.logoutTxt,gData.txt.autoLogoutTimeout,gData.changedPassTxt,gData.txt.autoLogoutLoginAgain,gData.txt.tooManyLogins];if("string"===typeof reasonTab[gData.loginReason]){html2.add(formContent,html2.p({},reasonTab[gData.loginReason]));}}else if(gData.falseUsername){html2.add(formContent,html2.p({},jsl.sprintf(gData.txt.notAuthorized,gData.falseUsername)));}else if(gData.showUserDialog){html2.add(formContent,html2.p({id:"uiUserLoginText"},gData.fromInternet?gData.txt.loginAgainUserMailPass:gData.txt.loginAgainUserPass));}else{html2.add(formContent,html2.p({id:"uiUserLoginText"},gData.isRemoteAuth?gData.txt.loginBoxPassword:gData.txt.loginAgainPass));}
if(true===gData.showUser){if(gData.fromInternet||!gData.activeUsers){gUsernameElem=html2.input({type:"text",id:"uiViewUser",name:"uiUser",tabindex:"1",value:gData.username});}else{if(1>gData.activeUsers.length){gUsernameElem=html2.input({type:"text",id:"uiViewUser",name:"uiUser",tabindex:"1",value:gData.username});}else{if(gData.username||gData.activeUsers.length===1){userOptions=gData.activeUsers;}else{userOptions=[{text:gData.txt.pleaseChoose,value:""}].concat(gData.activeUsers);}
gUsernameElem=html2.selectBoxPlain({id:"uiViewUser",name:"uiUser",selected:gData.username,options:userOptions,attr:{tabindex:"1"}});if(gData.simpleLoginPossible){jsl.addEventHandler(gUsernameElem,"change",function(){const passwordLabelDom=jsl.findFirst('label[for="uiPass"]')||"";if(jsl.getValue(gUsernameElem)===gData.migratedUser){jsl.setText(passwordLabelDom,gData.txt.boxPassword);jsl.removeClass("uiDefaultUserHint","hidden");jsl.addClass("uiHintChangeView","hidden");}else{jsl.setText(passwordLabelDom,gData.txt.pass);jsl.addClass("uiDefaultUserHint","hidden");jsl.removeClass("uiHintChangeView","hidden");}});}}}
jsl.addEventHandler(gUsernameElem,"change",function(){if(jsl.hasClass("uiViewUser","error")&&""!==jsl.getValue("uiViewUser")){jsl.removeClass("uiViewUser","error");jsl.addClass("uiUsernameError","hidden");}});usernameArea=html2.div({id:"uiUsernameArea"},html2.label({"for":"uiViewUser"},gData.txt.user),gUsernameElem,html2.br({}),gData.simpleLoginPossible&&html2.div({id:"uiDefaultUserHint",class:gData.migratedUser&&gData.username===gData.migratedUser?"":"hidden"},gData.txt.defaultUserHint),html2.p({id:"uiUsernameError","class":"ErrorMsg hidden"},gData.txt.chooseUsername));jsl.display(usernameArea,gData.showUserDialog);html2.add(formContent,usernameArea);}
passwordLabel=gData.txt.pass;if(gData.isRemoteAuth&&(gData.authMode==="1"||gData.simpleLoginPossible&&gData.startWithPasswordView)){passwordLabel=gData.txt.boxPassword;}else if(!gData.showUserDialog){passwordLabel=jsl.getTextByBoxType({box:gData.txt.boxPassword,rep:gData.txt.repeaterPassword,plc:gData.txt.powerlinePassword});}
html2.add(formContent,html2.passwordInput({id:"uiPass",name:"uiPass",label:passwordLabel,attr:{tabindex:"2",maxlength:"32",onkeyup:function(){if(jsl.hasClass(gPassElem,"error")&&""!==jsl.getValue(gPassElem)){jsl.removeClass(gPassElem,"error");jsl.addClass("uiLoginError","hidden");}}}}));gPassElem=jsl.get("uiPass");html2.add(formContent,html2.div({id:"uiLoginError","class":"hidden"},html2.p({"class":"error_text"},gData.txt.loginFailed),html2.p({"class":"error_text"},gData.txt.mistypedOrNotAuthorized),html2.p({id:"uiWait","class":"error_text"})));if(gData.showViewSwitchHint){otherUserLink=html2.link({attr:{class:"change-user-link"},callback:function(){jsl.setText("uiUserLoginText",gData.txt.loginAgainUserPass);jsl.display("uiUsernameArea",true);jsl.addClass("uiOtherUserLink","hidden");jsl.removeClass("uiPasswordLink","hidden");jsl.addClass("uiHintChangeView","hidden");jsl.setValue("viewInput","user");}});passwordLink=html2.link({attr:{class:"change-user-link"},callback:function(){jsl.setValue("uiViewUser",gData.migratedUser);jsl.removeClass("uiDefaultUserHint","hidden");jsl.setText(jsl.findFirst('label[for="uiPass"]')||"",gData.txt.boxPassword);jsl.setText("uiUserLoginText",gData.txt.loginBoxPassword);jsl.display("uiUsernameArea",false);jsl.removeClass("uiOtherUserLink","hidden");jsl.addClass("uiPasswordLink","hidden");jsl.setValue("viewInput","simple");}});html2.add(formContent,html2.br(),html2.hint({head:gData.txt.hint_headline,content:html2.fragment(html2.br(),html2.span({id:"uiOtherUserLink",class:gData.startWithPasswordView?"":"hidden"},html2.printf(gData.txt.loginWithAnotherUser,otherUserLink)),html2.span({id:"uiPasswordLink",class:gData.startWithPasswordView?"hidden":""},html2.printf(gData.txt.loginWithPassword,passwordLink))),attr:{id:"uiHintChangeView"}}));}
if(gData.showFactoryPasswordHint&&!gData.firstWizDone){html2.add(formContent,html2.div({},html2.p({"class":"hintMsg"},gData.txt.hint_headline),html2.p({},gData.txt.hintPassword)));}
if(gData.nbc){html2.add(formFoot,html2.input({type:"hidden",name:"nbc",value:"1"}));}
if(gData.temp_language){html2.add(formFoot,html2.input({type:"hidden",name:"temp_language",value:gData.temp_language}));}
if(gData.dbg){html2.add(formFoot,html2.input({type:"hidden",name:"dbg",value:gData.dbg}));}
if(gData.abortConfig){html2.add(formFoot,html2.input({type:"hidden",name:"abortConfig",value:"1"}));}
html2.add(formFoot,html2.input({type:"hidden",name:"response",id:"uiResp",value:""}),html2.input({type:"hidden",name:"lp",value:gData.lastPage}),html2.input({type:"hidden",name:"loginView",id:"viewInput",value:gData.startWithPasswordView?"simple":"user"}),html2.input({type:"hidden",name:"username",id:"username",value:gData.username}),html2.button({type:"submit",tabindex:"3",id:"submitLoginBtn"},gData.txt.login));if(!gData.fromInternet&&!gData.hideForgotPasswordLink){html2.add(formFoot,html2.a({onclick:showForgotPass},gData.txt.forgotPassword));}
return form;}
function createLanguageSelection(){var form,formContent,id,txt,divLang;txt={de:"Bitte wählen Sie Ihre Sprache aus.",en:"Please select your language.",es:"Por favor, seleccione su idioma.",fr:"Veuillez sélectionner votre langue.",it:"Selezionate la vostra lingua.",nl:"Selecteer uw taal.",pl:"Wybierz język."};form=html2.form({method:"post","action":"index.lua"});html2.add(gDialogContent,form);formContent=html2.div({"class":"language_selection formular"});html2.add(form,formContent);divLang=html2.div({});html2.add(formContent,html2.p({},txt.en));gData.languages.forEach(function(lang){if(lang.id!=="en"&&lang.currLang){html2.add(formContent,html2.p({},txt[lang.id]));}
id=html2.id("language",lang.id);html2.add(divLang,html2.div({"class":"formular"},html2.input({"type":"radio",name:"temp_language",value:lang.id,checked:lang.currLang,id:id}),html2.label({"for":id},lang.name)));});html2.add(formContent,divLang);html2.add(form,html2.div({"class":"btn_form_foot"},html2.button({type:"submit",tabindex:gData.languages.length+1,id:"submitLangBtn"},gData.txt.choose)));}
function get_perfTestResult(){if(gData.perfTestresults&&gData.perfTestresults.MEASURE_ECHO_STATUS!==undefined){if(3>gData.perfTestresults.MEASURE_ECHO_STATUS){return 0;}
if(4<gData.perfTestresults.MEASURE_ECHO_STATUS){return 1;}
if("number"!==typeof gData.perfTestresults.CABLE_NOK_DISTANCE){return 2;}
if(1>gData.perfTestresults.CABLE_NOK_DISTANCE){return 3;}
if(1<=gData.perfTestresults.CABLE_NOK_DISTANCE&&200>=gData.perfTestresults.CABLE_NOK_DISTANCE){return 4;}
if(200<gData.perfTestresults.CABLE_NOK_DISTANCE){return 5;}}
return-1;}
function get_perfTestTxt1(which){var txt,dslDownTime;dslDownTime=gData.perfTestresults.TIME_IN_STATE;txt=jsl.sprintf("Die DSL-Verbindung ist unterbrochen seit %1%Number%.",dslDownTime);switch(which){case 1:txt+=jsl.sprintf(" Die DSL-Leitung wurde getestet: Auf den ersten 200 Metern Leitung ab der FRITZ!Box wurde kein Problem festgestellt (Messung: vor %1%Time%).",gData.perfTestresults.TIME_SINCE_MEASUREMENT);break;case 2:txt+=jsl.sprintf(" Die DSL-Leitung wurde getestet: Die Unterbrechung der DSL-Leitung befindet sich innerhalb der ersten 200 Meter Leitung ab der FRITZ!Box (Messung: vor %1%Time%).",gData.perfTestresults.TIME_SINCE_MEASUREMENT);break;case 4:case 5:txt+=jsl.sprintf(" Die Unterbrechung der DSL-Leitung befindet sich etwa %1%Number% Meter Leitungslänge von der FRITZ!Box entfernt (Messung: vor %2%Time%).",gData.perfTestresults.CABLE_NOK_DISTANCE,gData.perfTestresults.TIME_SINCE_MEASUREMENT);break;}
return txt;}
function get_perfTestTxt2(which){var txt;switch(which){case 0:case 2:case 4:txt="Bitte prüfen Sie die Verkabelung zur Telefondose (TAE) und die Verkabelung im Haus.";break;case 1:case 5:txt="Bitte kontaktieren Sie Ihren DSL-Anbieter.";break;case 3:txt=jsl.sprintf("Schließen Sie das DSL-Kabel an die FRITZ!Box an, wenn Sie eine Internetverbindung über DSL aufbauen wollen (Messung: vor %1%Time%).",gData.perfTestresults.TIME_SINCE_MEASUREMENT);break;}
return txt;}
function doPerfTest(){function PerfTestResult(resp){var perfResult;if(resp){gData.perfTestresults=JSON.parse(resp||"{}");perfResult=get_perfTestResult();if(perfResult!==-1){jsl.setText(jsl.get("uiPerfTxt1"),get_perfTestTxt1(perfResult));jsl.setText(jsl.get("uiPerfTxt2"),get_perfTestTxt2(perfResult));window.setTimeout(doPerfTest,15000);}else{if(gXhrDsl){gXhrDsl.stop();}
jsl.hide("uiPerfTestHead");jsl.hide("uiPerfTestContent");}}}
gXhrDsl=http.request({method:"POST",url:"/",type:"text",params:{dsl:"1"},callback:PerfTestResult});gXhrDsl.start();}
function createPerfTestMsg(){var head=html2.div({"class":"perfTestHead",id:"uiPerfTestHead"}),content=html2.div({"class":"perfTestMsg",id:"uiPerfTestContent"}),perfResult=get_perfTestResult();jsl.setText(head,"Es besteht keine DSL-Verbindung");head.addEventListener("click",function(){if(jsl.hasClass(head,"show")){jsl.removeClass(head,"show");jsl.removeClass(content,"show");}else{jsl.addClass(head,"show");jsl.addClass(content,"show");}},false);html2.add(head,html2.span({}));html2.add(content,html2.p({id:"uiPerfTxt1"},get_perfTestTxt1(perfResult)));html2.add(content,html2.p({id:"uiPerfTxt2"},get_perfTestTxt2(perfResult)));html2.add(gDialogContent,head,content);window.setTimeout(doPerfTest,15000);}
function showPerfTestResults(){var perfResult;if(!gData.fromInternet&&gData.perfTestresults){if(gXhrDsl){gXhrDsl.stop();}
perfResult=get_perfTestResult();if(perfResult!==-1){createPerfTestMsg(perfResult);}}}
function createDialog(){var dialog=null,divContent=null;divContent=html2.div({id:"dialogContent","class":"dialog_content"});dialog=html2.div({"class":"dialog_outer"},html2.div({id:"dialogInner","class":"dialog_inner"},html2.div({id:"dialogHeadBox","class":"dialog_head_box "+(config.GUI_IS_REPEATER?"reppy":"fbox")},html2.h2({id:"dialogTitle"},gData.pageTitle||"")),divContent));html2.add(document.body,dialog);return{dialog:dialog,content:divContent};}
lib.init=function(data){var migratedUser,migratedUserList,lastWasMigrated;var dialog=null;if(!jsl||!md5||!html){return;}
gData=data;gData.challenge=gData.challenge||"";gData.fromInternet=gData.fromInternet||false;gData.pushBtnLogin=gData.pushBtnLogin||false;gData.activeUsers=(gData.activeUsers||[]);migratedUserList=(gData.activeUsers||[]).filter(function(u){return!!u.value&&u.value.match(/^fritz\d{4}$/);});if(localStorage){const lastUser=localStorage.getItem("lastUser");if(lastUser){for(const user of gData.activeUsers){const hash=window.generateUsernameHash(user.text);if(hash===lastUser){gData.username=user.text;}}}}
migratedUser=migratedUserList.length===1&&migratedUserList[0].value?migratedUserList[0].value:null;gData.migratedUser=migratedUser;lastWasMigrated=gData.username&&migratedUser===gData.username;gData.simpleLoginPossible=gData.showUser&&migratedUser;gData.startWithPasswordView=gData.activeUsers.length===1||lastWasMigrated||(migratedUser&&!gData.username);if(gData.loginView){gData.startWithPasswordView=gData.loginView==="simple";}
gData.showViewSwitchHint=gData.simpleLoginPossible&&gData.activeUsers.length>1;gData.showUserDialog=gData.showUser&&(!gData.simpleLoginPossible||!gData.startWithPasswordView);gData.isRemoteAuth=config.GUI_IS_REPEATER&&(gData.authMode==="1"||gData.authMode==="2");if(gData.simpleLoginPossible&&!gData.username){if(migratedUser){gData.username=migratedUser;}else if(gData.activeUsers.length===1){gData.username=gData.activeUsers[0].value;}}
if(!gFormElem){dialog=createDialog();gDialog=dialog.dialog;gDialogContent=dialog.content;if(gData.languages){gFormElem=createLanguageSelection();}else if(gData.pushBtnLogin){gFormElem=createPushBtnLoginForm();}else{gFormElem=createLoginForm();}
showPerfTestResults();}
if(gFormElem){if(!gData.showUser||(gUsernameElem&&0<gUsernameElem.value.length)){jsl.enable("submitLoginBtn");}
setFocus();gFormElem.onsubmit=onLoginFormSubmit;if(0<gData.blockTime){doBlockLogin(gData.blockTime*1000);}}};return lib;}());
